spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: '9789adfa150b1ffea6736a23c4998aec'
          naver:
            clientId: 'NVKXfWxvSbPyFaGdImAX'
            client-secret: 'HL4ytFnwx1'
          instagram:
            clientId: '227802223307140'
            client-secret: '7c96ea18efc734250f75736bef321906'
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'
          naver:
            devUserOauthId: 'oauthId'