spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 'edda58e2795afb0bd0867e7fb1da586c'
          naver:
            clientId: 'GBz97LY1fHbJ9ftJEfaq'
            client-secret: 'XFEFL6hmlf'
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'
          naver:
            devUserOauthId: 'oauthId'
api:
  kakao:
    key: 66cde5e53ebf0b49f4cc2f96aa169b6b
  weather:
    key: nw48C%2FaNZoCKw7bqaAuDAWjZCRG661IMhPwZyRGJ%2FknF31pOZcz4GpCDb7tH9MDecDtyXVSXKidnBiLLcILTSA%3D%3D