spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: '4a8b9a8b17ad40d0f9bb108612609561'
          naver:
            clientId: 'y2HKpmYpTcfaozTSMEiO'
            client-secret: 'UQvlfWAaD4'
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'
          naver:
            devUserOauthId: 'oauthId'
api:
  kakao:
    key: 66cde5e53ebf0b49f4cc2f96aa169b6b
  weather:
    key: nw48C%2FaNZoCKw7bqaAuDAWjZCRG661IMhPwZyRGJ%2FknF31pOZcz4GpCDb7tH9MDecDtyXVSXKidnBiLLcILTSA%3D%3D